service: sls-sqs-tutorial # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    QUEUE_URL: ${env:QUEUE_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
          - sqs:SendMessage
          - sqs:DeleteMessage
          - sqs:ReceiveMessage
      Resource: ${env:QUEUE_ARN}

functions:
  hello:
    handler: handler.hello
